#!/bin/sh /etc/rc.common

START=98
STOP=10
USE_PROCD=1

start_service() {
    [ -x /usr/bin/pisonet-agent ] || return 1
    [ -r /etc/pisonet-agent/config.json ] || return 1

    procd_open_instance
    procd_set_param command /usr/bin/pisonet-agent -config /etc/pisonet-agent/config.json
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param file /etc/pisonet-agent/config.json
    procd_set_param limits core="0"
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger pisonet-agent
}
